#ifndef TRANSFORMATIONS_H
#define TRANSFORMATIONS_H

#include "transformations/bin_gradient.h"
#include "transformations/bin_iterbimodal.h"
#include "transformations/bin_manual.h"
#include "transformations/bin_niblack.h"
#include "transformations/bin_otsu.h"
#include "transformations/blur_gaussian.h"
#include "transformations/blur_linear.h"
#include "transformations/blur_uniform.h"
#include "transformations/convolution.h"
#include "transformations/conversion_grayscale.h"
#include "transformations/corner_harris.h"
#include "transformations/correction.h"
#include "transformations/edge_canny.h"
#include "transformations/edge_laplacian.h"
#include "transformations/edge_prewitt.h"
#include "transformations/edge_roberts.h"
#include "transformations/edge_sobel.h"
#include "transformations/edge_zero.h"
#include "transformations/histogram_equalization.h"
#include "transformations/histogram_stretching.h"
#include "transformations/hough.h"
#include "transformations/hough_lines.h"
#include "transformations/hough_rectangles.h"
#include "transformations/map_height.h"
#include "transformations/map_horizon.h"
#include "transformations/map_normal.h"
#include "transformations/morph_dilate.h"
#include "transformations/morph_erode.h"
#include "transformations/morph_openclose.h"
#include "transformations/negative_image.h"
#include "transformations/noise_bilateral.h"
#include "transformations/noise_median.h"
#include "transformations/segmentation.h"

#endif // TRANSFORMATIONS_H
